name: open_words
description: "Simple implementation of a dictionary that allows you to write, group and repeat words in games."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.0
  flutter: 3.38.3

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1
  flutter_expandable_fab: ^2.5.2
  get_it: ^9.1.0
  logger: ^2.6.2
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  smooth_sheets: ^0.15.0
  vibration: ^3.1.4

  drift: ^2.29.0
  drift_flutter: ^0.2.7
  url_launcher: ^6.3.2

  http: ^1.6.0

  skeletonizer: ^2.1.0+1
  connectivity_plus: ^7.0.0
  flutter_animate: ^4.5.2
  share_plus: ^12.0.1
  uuid: ^4.5.2
  file_picker: ^10.3.7
  
  flutter_tts:
    git:
      url: https://github.com/sipasi/flutter_tts
      ref: master

  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  build_runner: ^2.6.0
  flutter_gen_runner: ^5.12.0

  drift_dev: ^2.29.0

flutter_gen:
  output: lib/core/generated/assets
  assets:
    outputs:
      directory_path_enabled: true

flutter:
  uses-material-design: true
  assets:
    - assets/json/dictionary/ukrainian/
    - assets/json/language/language-metadata.json
